language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true

before_script:
    - composer install --dev --no-interaction

script:
    - ./vendor/bin/phpunit
